name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Install sbt
      run: |
        wget https://github.com/sbt/sbt/releases/download/v1.9.8/sbt-1.9.8.tgz
        tar xf sbt-1.9.8.tgz
    - name: Install Verilator
      run: sudo apt-get install -y verilator
    - name: Run tests
      run: sbt/bin/sbt test
